plots:
  farm:
    # amount of these plots that the barn has in total
    amount: 10
    # offset to align the hologram properly
    holo-item-offset:
      x: 0
      y: 0.6
      z: 0.25
      yaw: 0
      pitch: 0
  animal:
    amount: 10
    holo-item-offset:
      x: 0
      y: 0.6
      z: 0.1
      yaw: 180
      pitch: 0
  silo:
    amount: 1
    holo-item-offset:
      x: 0.12
      y: 1.2
      z: -0.12
      yaw: 0
      pitch: 0
  barn:
    amount: 1
    holo-item-offset:
      x: 0
      y: 1
      z: 0
      yaw: 90
      pitch: 0