plots:
  farm:
    # offset to align the hologram properly
    holo-item-offset:
      x: 0
      y: 0.6
      z: 0.25
      yaw: 0
      pitch: 0
  animal:
    holo-item-offset:
      x: 0
      y: 0.6
      z: 0.1
      yaw: 180
      pitch: 0
  silo:
    holo-item-offset:
      x: 0.12
      y: 1.2
      z: -0.12
      yaw: 0
      pitch: 0
  barn:
    holo-item-offset:
      x: 0
      y: 1
      z: 0
      yaw: 90
      pitch: 0