name: BoFBarnCore
version: '${version}'
main: com.bof.core.Core
api-version: '1.20'
authors:
  - Wega
load: POSTWORLD
dependencies:
  server:
    BoFBarnWorldGenerator:
      load: BEFORE
      required: true
      join-classpath: true

